name: talk_explainer
description: A new Flutter project for speech transcription and explanation.

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  speech_to_text: ^6.6.2
  permission_handler: ^10.4.5

flutter:
  uses-material-design: true

dependency_overrides:
  permission_handler_apple: ^9.4.5