name: xplainr
description: Desktop assistant for live transcription and technical explanations.
version: 1.0.1+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
